name: twm
favicon: null
layout_spectrum: 0.8292940154206008
typography_spectrum: 0.2299830885604024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7760104860644788
  lightness: 0.36088137654587626
  saturation: 0.7061008505988866
  rhythmicContrast: 0.09064301964826882
purpose: []
